stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: chchdelm3/it-ggi

test:
  stage: test
  image: python3:latest
  script:
    - pip install -r requirements.txt

build:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker ps -a
    - docker buildx build --push \
      --platform linux/arm64,linux/amd64,linux/arm/v7 \
      --tag $IMAGE_NAME .

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker ps -a
    - docker container rm -f it-ggi
    - docker run -d -p 5000:5000 \
      --name it-ggi \
      --restart always \
      -e DATABASE_URL=mysql+pymysql://chatbot:checkitOut-2022@chatbotdb.c3hrvk4wz2vi.ap-northeast-2.rds.amazonaws.com:3306/test_db \
      -v ./log:/app/log \
      $IMAGE_NAME
    - docker ps -a

